In [1]:
import pandas as pd
from efficient_apriori import apriori

In [35]:
data = pd.read_csv('Market_Basket_Optimisation.csv', header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
data.loc[1].dropna().unique()

array(['burgers', 'meatballs', 'eggs'], dtype=object)

In [26]:
import numpy as np
transcation = np.array([data.loc[i].dropna().unique() for i in range(data.shape[0])])

In [34]:
items, rules = apriori(transcation, min_support=0.1, min_confidence=0.5)
print("频繁项集：", items)
print("关联规则：", rules)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()